<?php

namespace ContainerQbMRyc9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBillModelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Models\BillModel' shared autowired service.
     *
     * @return \App\Models\BillModel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Models/BillModel.php';

        return $container->privates['App\\Models\\BillModel'] = new \App\Models\BillModel();
    }
}
