<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzLx13P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzLx13P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUzLx13P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUzLx13P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUzLx13P\App_KernelDevDebugContainer([
    'container.build_hash' => 'UzLx13P',
    'container.build_id' => '04490841',
    'container.build_time' => 1659568360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzLx13P');
