<?php

namespace ContainerUzLx13P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MlLbqI0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mlLbqI0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mlLbqI0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'billModel' => ['privates', 'App\\Models\\BillModel', 'getBillModelService', true],
            'billRepository' => ['privates', 'App\\Repository\\BillRepository', 'getBillRepositoryService', true],
        ], [
            'billModel' => 'App\\Models\\BillModel',
            'billRepository' => 'App\\Repository\\BillRepository',
        ]);
    }
}
